### ISSUE TITLE
Messages do not refresh 

### ISSUE THREAD

**Issue by RomanRipp** [cometchat/cometchat-sample-app-ios#28]
**Describe the bug**
If one user is sending a message if another device has screen turned off, the receiver will not see the message until it reopenes messages view. 

**To Reproduce**
1. On device1, send a message. 
2. On device2, go to messages, message is viewable. 
3. Lock Screen on device2. 
3. On device1 send another message. 
4. Unlock device2, message is missing from the conversation. 

**Expected behavior**
When device is unlocked, messages are pulled. 

**Actual behavior**
When device is unlocked, messages are missing.

**Comment by pushpsenairekar2911** [comment]
Hi, 

We have added the fix for this in our latest releases of UI Kit, Please update your UI kit withe the latest one, 

Regard, 
Pushpsen R. Airekar
