### ISSUE TITLE
[v3.0.8-1] Uikit crashes

### ISSUE THREAD

**Issue by PauliusPetru** [cometchat/cometchat-sample-app-ios#31]
Uikit crashes on open.
file: CometChatMessageList.swift
function:     private func refreshMessageList(forID: String, type: CometChat.ReceiverType, scrollToBottom: Bool) 
line: 489
iOS: 15.4 (19E241)
CometChat SDK Version: v3.0.8-1

<img width="338" alt="Screenshot 2022-04-05 at 17 11 32" src="https://user-images.githubusercontent.com/26352359/161773535-9eace515-402b-4d98-8a00-d945a3742bae.png">

<img width="1054" alt="Screenshot 2022-04-05 at 17 13 41" src="https://user-images.githubusercontent.com/26352359/161773903-0010aef5-0a07-41bf-adcc-3d7da7ee9df4.png">

**Comment by PauliusPetru** [comment]
I cannot print value, it is stack trace from some user crash logs. It happened for one user multiple times. I cannot reproduce it on my device.

**Comment by proveshapyne** [comment]
Hey @PauliusPetru,

It would be great if we could connect to discuss this further. You can write to us at help@cometchat.com or reach out to us through [Intercom](https://www.cometchat.com/contact-support). We'll be happy to examine this further.

Regards,
Provesha

**Comment by vitaliyVCH** [comment]
Hello, is it possible for us to get count of all messages inside the conversation ?
