### ISSUE TITLE
[v3.0.8-1] CometChatSharedMedia  collectionView reload loop

### ISSUE THREAD

**Issue by PauliusPetru** [cometchat/cometchat-sample-app-ios#32]
CometChatSharedMedia collectionView reload loops on file representing. On my side it didn't show files so I started to debug uikit and noticed that after it fetches files calls `self?.collectionView.reloadData()` line `118` after this collection view delegates calls ` func collectionView(_ collectionView: UICollectionView, willDisplay cell: UICollectionViewCell, forItemAt indexPath: IndexPath)` line `366` which will try to fetch files again. So in that way it keeps reloading and fetching files.
file: CometChatSharedMedia.swift
function:   func refreshMediaMessages(for entity: AppEntity, type: CometChat.ReceiverType)
line: 118/366
iOS: 15.4.1(19E258)
CometChat SDK Version: v3.0.8-1

**Comment by ketanyekale** [comment]
Fixed with v4 SDKs and implemented in the latest sample app.
